{"name": "тест создания дубликата пользователя", "status": "passed", "description": "Ошибка при создании дубликата юзера", "start": 1718628603805, "stop": 1718628604029, "uuid": "1eaabc19-1446-4d7a-a862-92cc905c3e1c", "historyId": "4b5853239bc23668d3186cff9cc5e30c", "testCaseId": "4b5853239bc23668d3186cff9cc5e30c", "fullName": "tests.test_api_create_user.TestApiCreateUser#test_create_duplicate_user_error", "labels": [{"name": "feature", "value": "Проверка создания пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_create_user"}, {"name": "subSuite", "value": "TestApiCreateUser"}, {"name": "host", "value": "pc"}, {"name": "thread", "value": "17320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_create_user"}]}