{"name": "тест создания дубликата пользователя", "status": "passed", "description": "Ошибка при создании дубликата юзера", "start": 1719817015343, "stop": 1719817015656, "uuid": "87998527-3e6e-4af3-be8f-81ba62b28acf", "historyId": "4b5853239bc23668d3186cff9cc5e30c", "testCaseId": "4b5853239bc23668d3186cff9cc5e30c", "fullName": "tests.test_api_create_user.TestApiCreateUser#test_create_duplicate_user_error", "labels": [{"name": "feature", "value": "Проверка создания пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_create_user"}, {"name": "subSuite", "value": "TestApiCreateUser"}, {"name": "host", "value": "pc"}, {"name": "thread", "value": "14736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_create_user"}]}